apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-extra-cm
data:
  GF_AUTH_GENERIC_OAUTH_ENABLED: "{| CV_GF_AUTH_GENERIC_OAUTH_ENABLED |}"
  GF_SERVER_ROOT_URL: "{| CV_GF_SERVER_ROOT_URL |}"
  GF_AUTH_GENERIC_OAUTH_NAME: "{| CV_GF_AUTH_GENERIC_OAUTH_NAME |}"
  GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email"
  GF_AUTH_GENERIC_OAUTH_AUTH_URL: "{| CV_GF_AUTH_GENERIC_OAUTH_AUTH_URL |}"
  GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "{| CV_GF_AUTH_GENERIC_OAUTH_TOKEN_URL |}"
  GF_AUTH_GENERIC_OAUTH_API_URL: "{| CV_GF_AUTH_GENERIC_OAUTH_API_URL |}"
  GF_AUTH_SIGNOUT_REDIRECT_URL: "{| CV_GF_AUTH_SIGNOUT_REDIRECT_URL |}"
  GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH: "contains(groups[*], 'grafana-admin') && 'Admin' || contains(groups[*], 'grafana-editors') && 'Editor' || 'Viewer'"
  # 禁用登录表单，第一次可以设置为 false，第一个admin登录以后设置成grafana admin，后续这里可以设置为 true，关闭登录
  GF_AUTH_DISABLE_LOGIN_FORM: "{| CV_GF_AUTH_DISABLE_LOGIN_FORM |}"
